---
apiVersion: security.gardener.cloud/v1alpha1
kind: WorkloadIdentity
metadata:
  name: local
  namespace: garden-local
spec:
  audiences:
  - "provider-local"
  targetSystem:
    type: local
---
apiVersion: security.gardener.cloud/v1alpha1
kind: CredentialsBinding
metadata:
  name: local
  namespace: garden-local
credentialsRef:
  apiVersion: security.gardener.cloud/v1alpha1
  kind: WorkloadIdentity
  name: local
  namespace: garden-local
provider:
  type: local
